import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { FileText, Plus, Bot, Download } from "lucide-react";
import LinkedInShareButton from "@/components/osint_hub/LinkedInShareButton.jsx";
import { Button } from "@/components/ui/button";
import ReactMarkdown from "react-markdown";

export default function ReportsDashboard() {
  const qc = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [selected, setSelected] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [form, setForm] = useState({ title: "", report_type: "executive_summary", query: "" });

  const { data: reports = [], isLoading } = useQuery({ queryKey: ["osint_reports"], queryFn: () => base44.entities.OsintReport.list("-created_date", 100) });
  const { data: investigations = [] } = useQuery({ queryKey: ["investigations"], queryFn: () => base44.entities.OsintInvestigation.list("-created_date", 50) });

  const createMutation = useMutation({
    mutationFn: (data) => base44.entities.OsintReport.create({ ...data, status: "draft" }),
    onSuccess: (report) => { qc.invalidateQueries(["osint_reports"]); setShowForm(false); generateReport(report); }
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }) => base44.entities.OsintReport.update(id, data),
    onSuccess: () => qc.invalidateQueries(["osint_reports"])
  });

  const generateReport = async (report) => {
    setGenerating(true);
    const res = await base44.integrations.Core.InvokeLLM({
      prompt: `Generate a professional OSINT intelligence report in Markdown format.
Report Type: ${report.report_type}
Title: ${report.title}
Context: ${form.query || "General OSINT assessment"}

Structure the report as:
# ${report.title}
**Classification:** UNCLASSIFIED // FOR OFFICIAL USE ONLY
**Date:** ${new Date().toLocaleDateString()}
**Report Type:** ${report.report_type}
**Confidence Score:** [0-100]%

## Executive Summary
[2-4 sentence summary]

## Key Findings
[Bullet points with confidence scores]

## Risk Assessment
[Risk narrative with score]

## Indicators of Interest
[Any relevant IOCs found]

## Recommended Actions
[Prioritized action items]

## Source Citations
[Sources used]

---
*Generated by ASOSINT Reporting Agent*`
    });
    await base44.entities.OsintReport.update(report.id, {
      full_report_markdown: res,
      status: "final",
      confidence_score: 80,
    });
    qc.invalidateQueries(["osint_reports"]);
    setGenerating(false);
    setSelected(report.id);
  };

  const selectedReport = reports.find(r => r.id === selected);

  return (
    <div className="space-y-5 mt-4">
      <div className="flex justify-end">
        <Button onClick={() => setShowForm(!showForm)} className="bg-[#00d4ff]/10 border border-[#00d4ff]/20 text-[#00d4ff] hover:bg-[#00d4ff]/20 gap-2 text-sm">
          <Plus className="w-4 h-4" /> Generate Report
        </Button>
      </div>

      {showForm && (
        <div className="bg-[#0d1220] border border-[#00d4ff]/20 rounded-xl p-5 space-y-3">
          <p className="text-sm font-bold text-white">Generate Intelligence Report</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <input className="bg-[#111827] border border-white/10 rounded-lg px-3 py-2 text-sm text-white col-span-full" placeholder="Report title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} />
            <select className="bg-[#111827] border border-white/10 rounded-lg px-3 py-2 text-sm text-white" value={form.report_type} onChange={e => setForm({ ...form, report_type: e.target.value })}>
              {["executive_summary","technical","alert_brief","compromise_assessment","dark_web_summary","investigation"].map(v => <option key={v} value={v}>{v.replace(/_/g," ")}</option>)}
            </select>
            <textarea className="bg-[#111827] border border-white/10 rounded-lg px-3 py-2 text-sm text-white col-span-full h-16 resize-none" placeholder="Context / subject of report (e.g. investigation target, entity name, incident)" value={form.query} onChange={e => setForm({ ...form, query: e.target.value })} />
          </div>
          <div className="flex gap-2 justify-end">
            <Button variant="ghost" onClick={() => setShowForm(false)} className="text-gray-400 text-sm">Cancel</Button>
            <Button onClick={() => createMutation.mutate({ title: form.title, report_type: form.report_type })} disabled={!form.title || createMutation.isPending || generating} className="bg-[#00d4ff] text-black font-bold text-sm gap-1.5">
              <Bot className="w-4 h-4" />{generating ? "Generating..." : "Generate with AI"}
            </Button>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        <div className="bg-[#0d1220] border border-white/5 rounded-xl p-5 space-y-2">
          <div className="flex items-center gap-2 mb-3">
            <FileText className="w-4 h-4 text-[#00d4ff]" />
            <p className="text-sm font-bold text-white">Reports ({reports.length})</p>
          </div>
          {isLoading ? <p className="text-sm text-gray-600">Loading...</p> :
            reports.length === 0 ? <p className="text-sm text-gray-600">No reports yet.</p> :
            reports.map(r => (
              <button key={r.id} onClick={() => setSelected(r.id === selected ? null : r.id)}
                className={`w-full text-left px-3 py-2.5 rounded-lg border transition-all ${selected === r.id ? "border-[#00d4ff]/30 bg-[#00d4ff]/5" : "border-white/5 bg-[#111827] hover:border-white/10"}`}>
                <p className="text-xs font-semibold text-gray-200 truncate">{r.title}</p>
                <div className="flex items-center gap-2 mt-1">
                  <span className="text-[9px] px-1.5 py-0.5 rounded bg-white/5 text-gray-500">{r.report_type?.replace(/_/g," ")}</span>
                  <span className={`text-[9px] font-bold ${r.status === "final" ? "text-[#2ed573]" : "text-[#ffa502]"}`}>{r.status?.toUpperCase()}</span>
                </div>
              </button>
            ))
          }
        </div>

        <div className="lg:col-span-2 bg-[#0d1220] border border-white/5 rounded-xl p-5">
          {selectedReport ? (
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <p className="text-sm font-bold text-white">{selectedReport.title}</p>
                <div className="flex items-center gap-2">
                <LinkedInShareButton prefillContent={selectedReport.executive_summary || selectedReport.title} report={selectedReport} />
                <Button onClick={() => { const blob = new Blob([selectedReport.full_report_markdown || ""], { type: "text/markdown" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `${selectedReport.title}.md`; a.click(); }}
                  className="text-xs gap-1.5 bg-white/5 hover:bg-white/10 text-gray-400">
                  <Download className="w-3.5 h-3.5" /> Export
                </Button>
              </div>
              </div>
              {selectedReport.full_report_markdown ? (
                <div className="prose prose-sm prose-invert max-w-none bg-[#111827] rounded-lg p-4 border border-white/5 max-h-[60vh] overflow-y-auto">
                  <ReactMarkdown>{selectedReport.full_report_markdown}</ReactMarkdown>
                </div>
              ) : (
                <div className="flex items-center justify-center h-40 text-gray-600 text-sm">Report content not yet generated.</div>
              )}
            </div>
          ) : (
            <div className="flex items-center justify-center h-full min-h-[200px] text-gray-600 text-sm">Select a report to view its contents</div>
          )}
        </div>
      </div>
    </div>
  );
}