import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';
import { jsPDF } from 'npm:jspdf@4.0.0';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    // Fetch all data in parallel
    const [findings, scans, advisories, assets] = await Promise.all([
      base44.asServiceRole.entities.VulnerabilityFinding.list('-priority_score', 200),
      base44.asServiceRole.entities.VulnerabilityScan.list('-created_date', 10),
      base44.asServiceRole.entities.VendorAdvisory.list('-created_date', 50),
      base44.asServiceRole.entities.Asset.list('-created_date', 100),
    ]);

    const doc = new jsPDF();
    const margin = 15;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const maxWidth = pageWidth - margin * 2;
    let y = 0;

    const checkPage = (needed = 10) => {
      if (y + needed > pageHeight - 20) {
        doc.addPage();
        y = 20;
      }
    };

    const addText = (text, x, size = 10, color = [60, 60, 60], style = 'normal') => {
      doc.setFontSize(size);
      doc.setTextColor(...color);
      doc.setFont('helvetica', style);
      const lines = doc.splitTextToSize(String(text), maxWidth - (x - margin));
      checkPage(lines.length * 6 + 4);
      doc.text(lines, x, y);
      y += lines.length * 6 + 2;
    };

    const addSection = (title) => {
      checkPage(18);
      y += 4;
      doc.setFillColor(15, 25, 50);
      doc.rect(margin, y - 5, maxWidth, 12, 'F');
      doc.setFontSize(11);
      doc.setTextColor(0, 212, 255);
      doc.setFont('helvetica', 'bold');
      doc.text(title.toUpperCase(), margin + 3, y + 3);
      y += 12;
    };

    const addKV = (label, value, col = [60, 60, 60]) => {
      checkPage(8);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(80, 80, 80);
      doc.text(`${label}:`, margin, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...col);
      doc.text(String(value), margin + 45, y);
      y += 6;
    };

    // ─── COVER PAGE ─────────────────────────────────────────────────────────
    doc.setFillColor(10, 14, 26);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');

    doc.setFillColor(0, 212, 255);
    doc.rect(0, 0, pageWidth, 3, 'F');

    doc.setFontSize(26);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 212, 255);
    doc.text('ASOSINT', margin, 55);

    doc.setFontSize(18);
    doc.setTextColor(255, 255, 255);
    doc.text('Security Posture Report', margin, 70);

    doc.setFontSize(11);
    doc.setTextColor(150, 160, 180);
    doc.text('Executive Leadership Summary', margin, 82);

    doc.setFillColor(20, 30, 55);
    doc.roundedRect(margin, 100, maxWidth, 50, 3, 3, 'F');

    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const openFindings = findings.filter(f => f.status === 'open');
    const criticalOpen = findings.filter(f => f.severity === 'critical' && f.status === 'open');
    const exploited = findings.filter(f => f.actively_exploited && f.status === 'open');
    const lastScan = scans[0];

    doc.setFontSize(10);
    doc.setTextColor(200, 210, 230);
    doc.setFont('helvetica', 'normal');
    const meta = [
      `Report Date: ${dateStr}`,
      `Generated By: ${user.full_name || user.email}`,
      `Total Findings Analyzed: ${findings.length}`,
      `Open Vulnerabilities: ${openFindings.length}`,
      `Critical / Actively Exploited: ${criticalOpen.length} / ${exploited.length}`,
      `Last Scan: ${lastScan ? new Date(lastScan.created_date).toLocaleDateString() : 'N/A'}`,
    ];
    meta.forEach((line, i) => {
      doc.text(line, margin + 5, 113 + i * 6);
    });

    doc.setFontSize(8);
    doc.setTextColor(80, 90, 110);
    doc.text('CLASSIFICATION: SENSITIVE — FOR LEADERSHIP USE ONLY', margin, pageHeight - 15);
    doc.text(`Page 1`, pageWidth - margin - 10, pageHeight - 15);

    // ─── PAGE 2: EXECUTIVE SUMMARY ──────────────────────────────────────────
    doc.addPage();
    y = 20;

    // Header bar on each content page
    doc.setFillColor(10, 14, 26);
    doc.rect(0, 0, pageWidth, 12, 'F');
    doc.setFontSize(8);
    doc.setTextColor(0, 180, 220);
    doc.setFont('helvetica', 'bold');
    doc.text('ASOSINT · SECURITY POSTURE REPORT', margin, 8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 110, 130);
    doc.text(dateStr, pageWidth - margin - 30, 8);
    y = 22;

    addSection('Executive Summary');

    // Risk score calculation
    const riskScore = Math.min(100, Math.round(
      (criticalOpen.length * 20) +
      (exploited.length * 25) +
      (findings.filter(f => f.severity === 'high' && f.status === 'open').length * 8) +
      (findings.filter(f => f.severity === 'medium' && f.status === 'open').length * 3)
    ));
    const riskLabel = riskScore >= 70 ? 'CRITICAL' : riskScore >= 40 ? 'HIGH' : riskScore >= 20 ? 'MEDIUM' : 'LOW';
    const riskColor = riskScore >= 70 ? [220, 50, 50] : riskScore >= 40 ? [230, 120, 30] : riskScore >= 20 ? [200, 160, 0] : [40, 180, 80];

    // Risk gauge box
    doc.setFillColor(20, 30, 50);
    doc.roundedRect(margin, y, maxWidth, 24, 2, 2, 'F');
    doc.setFontSize(18);
    doc.setFont('helvetica', 'black');
    doc.setTextColor(...riskColor);
    doc.text(`OVERALL RISK: ${riskLabel}`, margin + 5, y + 15);
    doc.setFontSize(10);
    doc.setTextColor(150, 160, 180);
    doc.setFont('helvetica', 'normal');
    doc.text(`Composite Risk Score: ${riskScore}/100`, pageWidth - margin - 50, y + 15);
    y += 30;

    addText(`This report summarizes the current security posture across ${assets.length} monitored assets. The platform identified ${findings.length} total vulnerability findings, of which ${openFindings.length} remain open. Immediate attention is recommended for ${criticalOpen.length} critical severity findings and ${exploited.length} actively exploited vulnerabilities.`, margin, 10);
    y += 2;

    // Summary stats grid
    const stats = [
      { label: 'Total Findings', value: findings.length, c: [100, 100, 200] },
      { label: 'Open', value: openFindings.length, c: [220, 140, 0] },
      { label: 'Critical Open', value: criticalOpen.length, c: [220, 50, 50] },
      { label: 'Exploited', value: exploited.length, c: [220, 50, 50] },
      { label: 'In Remediation', value: findings.filter(f => f.status === 'in_remediation').length, c: [0, 150, 220] },
      { label: 'Resolved', value: findings.filter(f => f.status === 'resolved').length, c: [40, 180, 80] },
    ];

    checkPage(30);
    const cellW = maxWidth / 3;
    const cellH = 20;
    stats.forEach((s, i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const cx = margin + col * cellW;
      const cy = y + row * (cellH + 3);
      doc.setFillColor(18, 28, 50);
      doc.roundedRect(cx, cy, cellW - 3, cellH, 2, 2, 'F');
      doc.setFontSize(16);
      doc.setFont('helvetica', 'black');
      doc.setTextColor(...s.c);
      doc.text(String(s.value), cx + 5, cy + 12);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(130, 140, 160);
      doc.text(s.label, cx + 5, cy + 18);
    });
    y += (Math.ceil(stats.length / 3)) * (cellH + 3) + 8;

    // ─── SCAN RESULTS ───────────────────────────────────────────────────────
    addSection('Latest Scan Results');

    if (scans.length === 0) {
      addText('No scans have been performed yet.', margin, 10, [150, 150, 150], 'italic');
    } else {
      scans.slice(0, 5).forEach((scan, idx) => {
        checkPage(30);
        doc.setFillColor(15, 22, 40);
        doc.roundedRect(margin, y, maxWidth, 26, 2, 2, 'F');

        const statusColor = scan.status === 'completed' ? [40, 180, 80] : scan.status === 'running' ? [0, 180, 220] : [180, 80, 80];
        doc.setFillColor(...statusColor);
        doc.rect(margin, y, 3, 26, 'F');

        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(200, 210, 230);
        doc.text(`Scan #${idx + 1}: ${scan.scan_type || 'vulnerability_scan'}`.toUpperCase(), margin + 7, y + 8);

        doc.setFont('helvetica', 'normal');
        doc.setTextColor(130, 140, 160);
        const scanMeta = [
          `Date: ${new Date(scan.created_date).toLocaleDateString()}`,
          `Status: ${(scan.status || 'unknown').toUpperCase()}`,
          `Findings: ${scan.findings_count || 0}`,
          `Critical: ${scan.critical_count || 0}`,
        ].join('   |   ');
        doc.text(scanMeta, margin + 7, y + 18);
        y += 30;
      });
    }

    // ─── TRENDING VULNERABILITY COUNTS ──────────────────────────────────────
    addSection('Trending Vulnerability Counts');

    // Group by severity
    const bySeverity = { critical: 0, high: 0, medium: 0, low: 0, informational: 0 };
    findings.forEach(f => { bySeverity[f.severity] = (bySeverity[f.severity] || 0) + 1; });

    const sevColors = {
      critical: [220, 50, 50],
      high: [220, 120, 30],
      medium: [200, 160, 0],
      low: [60, 160, 220],
      informational: [100, 110, 130],
    };

    checkPage(50);
    const barMax = Math.max(...Object.values(bySeverity), 1);
    const barAreaW = maxWidth - 60;
    Object.entries(bySeverity).forEach(([sev, count]) => {
      const barW = (count / barMax) * barAreaW;
      const c = sevColors[sev] || [100, 100, 100];
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(160, 170, 190);
      doc.text(sev.toUpperCase(), margin, y + 5);
      doc.setFillColor(20, 30, 50);
      doc.rect(margin + 42, y, barAreaW, 8, 'F');
      if (barW > 0) {
        doc.setFillColor(...c);
        doc.rect(margin + 42, y, barW, 8, 'F');
      }
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...c);
      doc.text(String(count), margin + 44 + barAreaW + 3, y + 6);
      y += 12;
    });

    // Group by type
    y += 4;
    const byType = {};
    findings.forEach(f => {
      const t = f.vulnerability_type || 'unknown';
      byType[t] = (byType[t] || 0) + 1;
    });
    const topTypes = Object.entries(byType).sort((a, b) => b[1] - a[1]).slice(0, 6);

    addText('Distribution by Vulnerability Type:', margin, 9, [130, 140, 160], 'bold');
    checkPage(topTypes.length * 7 + 10);
    topTypes.forEach(([type, count]) => {
      addKV(type.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()), `${count} finding${count !== 1 ? 's' : ''}`, [180, 190, 210]);
    });

    // ─── TOP RISK MITIGATION PRIORITIES ─────────────────────────────────────
    addSection('Top Risk Mitigation Priorities');

    const topFindings = findings
      .filter(f => f.status === 'open' || f.status === 'in_remediation')
      .sort((a, b) => {
        const sevScore = { critical: 4, high: 3, medium: 2, low: 1 };
        const aScore = (sevScore[a.severity] || 0) * 10 + (a.actively_exploited ? 15 : 0) + (a.priority_score || 0) / 10;
        const bScore = (sevScore[b.severity] || 0) * 10 + (b.actively_exploited ? 15 : 0) + (b.priority_score || 0) / 10;
        return bScore - aScore;
      })
      .slice(0, 10);

    if (topFindings.length === 0) {
      addText('No open findings requiring remediation at this time.', margin, 10, [40, 180, 80]);
    } else {
      topFindings.forEach((f, idx) => {
        checkPage(34);
        const c = sevColors[f.severity] || [100, 100, 130];
        doc.setFillColor(15, 22, 40);
        doc.roundedRect(margin, y, maxWidth, 28, 2, 2, 'F');
        doc.setFillColor(...c);
        doc.rect(margin, y, 3, 28, 'F');

        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(200, 210, 230);
        const title = `${idx + 1}. ${f.title || f.cve_id || 'Untitled Finding'}`;
        const titleLines = doc.splitTextToSize(title, maxWidth - 20);
        doc.text(titleLines[0], margin + 7, y + 8);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...c);
        doc.text((f.severity || 'unknown').toUpperCase(), margin + 7, y + 16);
        if (f.actively_exploited) {
          doc.setTextColor(220, 80, 80);
          doc.text('⚠ ACTIVELY EXPLOITED', margin + 45, y + 16);
        }
        doc.setTextColor(100, 110, 130);
        doc.text(`Asset: ${f.affected_asset || 'Unknown'}   |   CVSS: ${f.cvss_score || 'N/A'}   |   Priority Score: ${Math.round(f.priority_score || 0)}`, margin + 7, y + 23);
        y += 32;
      });
    }

    // ─── VENDOR ADVISORIES SUMMARY ───────────────────────────────────────────
    if (advisories.length > 0) {
      addSection('Vendor Advisory Highlights');
      const critAdvisories = advisories.filter(a => a.severity === 'critical' || a.severity === 'high').slice(0, 5);
      if (critAdvisories.length > 0) {
        critAdvisories.forEach(a => {
          checkPage(18);
          addKV(a.vendor_name || 'Unknown Vendor', `${a.title} — ${(a.severity || '').toUpperCase()}`, [200, 180, 100]);
        });
      } else {
        addText('No critical or high severity vendor advisories pending.', margin, 10, [40, 180, 80]);
      }
    }

    // ─── RECOMMENDATIONS ────────────────────────────────────────────────────
    addSection('Strategic Recommendations');

    const recommendations = [];
    if (exploited.length > 0)
      recommendations.push(`Immediately patch or isolate ${exploited.length} actively exploited vulnerability${exploited.length > 1 ? 'ies' : 'y'} — these represent the highest operational risk.`);
    if (criticalOpen.length > 0)
      recommendations.push(`Prioritize remediation of ${criticalOpen.length} critical-severity findings within the next 24–72 hours.`);
    if (findings.filter(f => f.status === 'open' && f.severity === 'high').length > 0)
      recommendations.push(`Address ${findings.filter(f => f.status === 'open' && f.severity === 'high').length} high-severity findings within the next 7 days.`);
    if (scans.length === 0 || (lastScan && (Date.now() - new Date(lastScan.created_date).getTime()) > 7 * 24 * 60 * 60 * 1000))
      recommendations.push('Schedule a full vulnerability scan — last scan is over 7 days old or has not been run.');
    if (advisories.filter(a => a.status === 'new').length > 0)
      recommendations.push(`Triage ${advisories.filter(a => a.status === 'new').length} new vendor advisories that have not yet been reviewed.`);
    if (recommendations.length === 0)
      recommendations.push('No immediate critical actions required. Maintain regular scanning cadence and monitor new advisories.');

    recommendations.forEach((rec, i) => {
      checkPage(16);
      doc.setFillColor(15, 25, 45);
      doc.roundedRect(margin, y, maxWidth, 14, 2, 2, 'F');
      doc.setFillColor(0, 180, 100);
      doc.rect(margin, y, 3, 14, 'F');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(200, 220, 200);
      doc.text(`${i + 1}.`, margin + 6, y + 9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(180, 190, 200);
      const recLines = doc.splitTextToSize(rec, maxWidth - 18);
      doc.text(recLines[0], margin + 13, y + 9);
      y += 18;
    });

    // ─── FOOTER ON ALL PAGES ─────────────────────────────────────────────────
    const pageCount = doc.getNumberOfPages();
    for (let i = 2; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFillColor(10, 14, 26);
      doc.rect(0, pageHeight - 14, pageWidth, 14, 'F');
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 80, 100);
      doc.text('ASOSINT · Security Posture Report · SENSITIVE', margin, pageHeight - 5);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, pageHeight - 5);
    }

    const pdfBytes = doc.output('arraybuffer');
    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="ASOSINT_Security_Posture_Report_${now.toISOString().split('T')[0]}.pdf"`,
      },
    });
  } catch (error) {
    console.error('PDF generation error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});